spring:
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/OpenElectives
    username: postgres
    password: Password@123
    driverClassName: org.postgresql.Driver
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: update
